---
#
# Configure FreeRADIUS per eduroam technical documentation at
# https://wiki.geant.org/display/H2eduroam/freeradius-idp
# (as at v.27 dated 9 August 2017)
# As noted there, you must complete the SP configuration first
#
- name: Override the eap module config in the FreeRADIUS approved way
  become: yes
  block:
    - name: Check whether we've overwritten the default eap module
      stat:
        path: /etc/freeradius/mods-enabled/eap
        follow: no
        get_attributes: no
        get_checksum: no
        get_md5: no
        get_mime: no
      register: eap
    - name: Disable the default eap module
      file:
        path: /etc/freeradius/mods-enabled/eap
        state: absent
      when: eap.stat.islnk is defined and eap.stat.islnk
    - name: Install a new eduroam-ish eap module
      template:
        src: mods-available/eap.j2
        dest: /etc/freeradius/mods-enabled/eap
      notify:
        - restart freeradius
  tags: [ freeradius, freeradius-config, eduroam-idp ]

- name: Configure eduroam-inner-tunnel virtual site
  become: yes
  template:
    src: sites-available/eduroam-inner-tunnel.j2
    dest: /etc/freeradius/sites-available/eduroam-inner-tunnel
  notify:
    - restart freeradius
  tags: [ freeradius, freeradius-config, eduroam-idp ]

- name: Enable eduroam-inner-tunnel virtual site
  become: yes
  file:
    state: link
    src: /etc/freeradius/sites-available/eduroam-inner-tunnel
    path: /etc/freeradius/sites-enabled/eduroam-inner-tunnel
  notify:
    - restart freeradius
  tags: [ freeradius, freeradius-config, eduroam-idp ]

- name: Create a users file
  become: yes
  template:
    src: mods-config/files/authorize.j2
    dest: /etc/freeradius/mods-config/files/authorize
  notify:
    - restart freeradius
  tags: [ freeradius, freeradius-config, eduroam-idp ]

- name: Enable the PAM module
  become: yes
  file:
    state: link
    src: /etc/freeradius/mods-available/pam
    path: /etc/freeradius/mods-enabled/pam
  when: use_pam is defined and use_pam
  notify:
    - restart freeradius
  tags: [ freeradius, freeradius-config, eduroam-idp ]

- name: Override the ldap module config in the FreeRADIUS approved way
  become: yes
  block:
    - name: Check whether we've overwritten the default ldap module
      stat:
        path: /etc/freeradius/mods-enabled/ldap
        follow: no
        get_attributes: no
        get_checksum: no
        get_md5: no
        get_mime: no
      register: ldap
    - name: Disable the default ldap module
      file:
        path: /etc/freeradius/mods-enabled/ldap
        state: absent
      when: ldap.stat.islnk is defined and ldap.stat.islnk
    - name: Install a new eduroam-ish ldap module
      template:
        src: mods-available/ldap.j2
        dest: /etc/freeradius/mods-enabled/ldap
      notify:
        - restart freeradius
  when: use_ldap is defined and use_ldap
  tags: [ freeradius, freeradius-config, eduroam-idp ]

- name: Create an ldap instantiation config
  become: yes
  block:
     - name: create ldap mods-config directory
       file:
         path: /etc/freeradius/mods-config/ldap
         state: directory
         mode: 0755
     - name: create an ldap instantiation config in mods-config
       template:
         src: mods-config/ldap/instantiate.j2
         dest: /etc/freeradius/mods-config/ldap/instantiate
     - name: add a line to the instantiate block
       lineinfile:
         path: /etc/freeradius/radiusd.conf
         regexp: "^\\$INCLUDE mods-config/ldap/instantiate"
         line: "$INCLUDE mods-config/ldap/instantiate"
         state: present
         insertafter: "^instantiate\\s*{"
  when: use_ldap is defined and use_ldap
  tags: [ freeradius, freeradius-config, eduroam-idp ]

- name: Seed a secret for Chargeable-User-Identity
  become: yes
  replace:
    path: /etc/freeradius/policy.d/cui
    regexp: "^cui_hash_key\\s*=\\s*[\"']changeme[\"']?\\s*$"
    replace: "cui_hash_key = \"{{ lookup('password', '/dev/null') }}\""
  when: send_cui is defined and send_cui
  notify:
    - restart freeradius
  tags: [ freeradius, freeradius-config, eduroam-idp ]
